import React from 'react';
function Contact () {    return (    
      <div class="container mt-4">            <div class="row">                <div class="col">       
                  <div class="container mt-4">                      <div class="row">                        
                   <div class="col-4">                         <div class="row ">                    
                          <div class="col-3">                             <div>                         
                            
                                    <img src="https://i.pinimg.com/564x/bd/e5/e5/bde5e5f37a7c64ea5700b049b7e424c9.jpg"                              width="50" height="50" alt="pictures" title="running with these is not recommended"                            /></div></div>                                                        <div class="col-8">                                <h4>Location</h4>                                <p>43 Raymouth Rd. Baltemoer, London 3910</p>                            </div>                            </div>                            <div class="row ">                           <div class="col-3">                             <div>                                 <img src="https://icons-for-free.com/iconfiles/png/512/clock+event+time+icon-1320196391238140860.png"                              width="50" height="50" alt="pictures" title="running with these is not recommended"                            /></div></div>                                                        <div class="col-8">                                <h4>Open hours</h4>                                <p>Sunday-friday : 11:00 AM - 23:00 PM</p>                            </div>                            </div>                            <div class="row ">                           <div class="col-3">                             <div>                                 <img src="https://i.pinimg.com/564x/ed/07/d0/ed07d0a624143e28db8a98526043dc58.jpg"      
                                           width="50" height="50" alt="pictures" title="running with these is not recommended"                            /></div></div>                                                        <div class="col-8">                                <h4>Email</h4>                                <p>Info@gmail.com</p>                            </div>                            </div>                            <div class="row ">                           <div class="col-3">                             <div>                                 <img src="https://i.pinimg.com/564x/88/a9/d0/88a9d0c252977e827f7f3862e8de6714.jpg"                              width="50" height="50"  alt="pictures" title="running with these is not recommended"                            /></div></div>                                                        <div class="col-8">                                <h4>call:</h4>                                <p>+12345667889</p>                            </div>                            </div>                           </div>                       <div class="col-8">                           <div class="row">                              <div class="col">                               <div class="input-group mb-3">                               <input type="text" class="form-control" placeholder="your name" aria-label="name" aria-describedby="basic-addon1"></input>                               </div>                         </div>                           <div class="col">                           <div class="input-group mb-3">                             <input type="email" class="form-control" placeholder="your email" aria-label="email" aria-describedby="basic-addon1"></input>                           </div>                           </div>                           </div>                           <div class="row">                           <div class="input-group mb-3">                          <input type="text" class="form-control" placeholder="Subject" aria-label="subject" aria-describedby="basic-addon1"></input>                            </div>                           </div>                              <div class="row">                           <div class="input-group">                                 <textarea  placeholder="message" class="form-control" aria-label="With textarea"></textarea>                            </div>                          </div>                         <br></br>                     <div class="btn-group" role="group" aria-label="Basic example" >                               <button  type="button" class="btn btn-primary">Send message</button>                              </div>                                </div>                                            </div>                  </div>                </div>            </div>       
                   </div>    );}
                   export default Contact;